# Application Name
spring.application.name=hostelmanagement

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/hostel_db
spring.datasource.username=root
spring.datasource.password=Parth@1475
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Brevo Mail Configuration
brevo.api.url=https://api.brevo.com/v3/smtp/email
brevo.api.key=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
brevo.sender.name=Hostel Management
brevo.sender.email=hostelease123@gmail.com

# JWT Security Configuration
application.security.jwt.secret-key=fasdhfasdfarutrtbkjadfhabcdfhkasdlafshdfsfdf
# 24 hours in milliseconds = 86400000
application.security.jwt.expiration=86400000

# CORS Configuration
app.cors.allowed-origins=http://localhost:5173
